# Generated by Django 2.2.7 on 2019-12-04 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgu', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=2, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('disponibilidadeAtendimento', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('vinculo', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira_de_Rodas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome_pessoa', models.CharField(max_length=120)),
                ('nome_curso', models.CharField(blank=True, max_length=120, null=True)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('data_devolucao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DiasAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaAtendimento', models.CharField(max_length=20)),
                ('horarioInicio', models.TimeField()),
                ('horarioTermino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=120)),
                ('quantidade', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeficiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='alteridade.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=120)),
                ('sexo', models.CharField(max_length=2)),
                ('dataNascimento', models.DateField()),
                ('numeroAcademico', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('periodo', models.CharField(blank=True, max_length=5, null=True)),
                ('possuiDeficiencia', models.CharField(blank=True, max_length=100, null=True)),
                ('recebeuAuxilioNucleo', models.CharField(blank=True, max_length=100, null=True)),
                ('disciplina', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=6)),
                ('professor', models.CharField(max_length=120)),
                ('tipoAuxilio', models.CharField(blank=True, max_length=120, null=True)),
                ('monitor', models.CharField(max_length=120)),
                ('observacoes', models.CharField(blank=True, max_length=200, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('inscricao', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField()),
                ('sabendo_grupo', models.CharField(blank=True, max_length=200, null=True)),
                ('expectativas', models.CharField(blank=True, max_length=200, null=True)),
                ('horarios_disponiveis', models.CharField(max_length=200)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Academico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Curso')),
                ('nome_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=False, max_length=120)),
                ('cgu', models.CharField(default=False, max_length=11, unique=True)),
                ('CPF', models.CharField(default=False, max_length=11, unique=True)),
                ('telefone', models.CharField(default=False, max_length=12)),
                ('tipoEstagiario', models.IntegerField()),
                ('diasAtendimento', models.ManyToManyField(default='', to='alteridade.DiasAtendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, max_length=120, null=True)),
                ('people', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('livro', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('frequenciaAcademico', models.IntegerField(null=True)),
                ('frequenciaEstagiario', models.IntegerField(null=True)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Academico')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Estagiario')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alteridade.Recurso')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Servico')),
            ],
        ),
        migrations.AddField(
            model_name='academico',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alteridade.Curso'),
        ),
        migrations.AddField(
            model_name='academico',
            name='tipoDeficiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alteridade.TipoDeficiencia'),
        ),
    ]
