# Generated by Django 2.2.7 on 2019-12-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alteridade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diasatendimento',
            old_name='horarioInicio',
            new_name='horario_inicio',
        ),
        migrations.RenameField(
            model_name='diasatendimento',
            old_name='horarioTermino',
            new_name='horario_termino',
        ),
    ]
