# Generated by Django 2.2.7 on 2019-12-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alteridade', '0002_auto_20191204_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
