# Generated by Django 2.2.7 on 2019-12-06 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alteridade', '0003_auto_20191205_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biblioteca',
            old_name='curso',
            new_name='curse',
        ),
    ]
